# Generated by Django 4.1.1 on 2022-11-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookValue', models.FloatField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=100, null=True)),
                ('currentPrice', models.FloatField(blank=True, null=True)),
                ('currentRatio', models.FloatField(blank=True, null=True)),
                ('debtToEquity', models.FloatField(blank=True, null=True)),
                ('dividendRate', models.FloatField(blank=True, null=True)),
                ('dividendYield', models.FloatField(blank=True, null=True)),
                ('enterpriseValue', models.BigIntegerField(blank=True, null=True)),
                ('expectedReturn', models.FloatField(blank=True, default=None, null=True)),
                ('exchange', models.CharField(blank=True, max_length=100, null=True)),
                ('exchangeTimezoneName', models.CharField(blank=True, max_length=100, null=True)),
                ('exchangeTimezoneShortName', models.CharField(blank=True, max_length=100, null=True)),
                ('fairValue', models.FloatField(blank=True, default=0, null=True)),
                ('financialCurrency', models.CharField(blank=True, max_length=100, null=True)),
                ('fiveYearAvgDividendYield', models.FloatField(blank=True, null=True)),
                ('forwardEps', models.FloatField(blank=True, null=True)),
                ('forwardPE', models.FloatField(blank=True, null=True)),
                ('freeCashflow', models.BigIntegerField(blank=True, null=True)),
                ('fullTimeEmployees', models.BigIntegerField(blank=True, null=True)),
                ('grossMargins', models.FloatField(blank=True, null=True)),
                ('grossProfits', models.BigIntegerField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=100, null=True)),
                ('longName', models.CharField(blank=True, max_length=100, null=True)),
                ('market', models.CharField(blank=True, max_length=100, null=True)),
                ('marketCap', models.BigIntegerField(blank=True, null=True)),
                ('mostRecentQuarter', models.BigIntegerField(blank=True, null=True)),
                ('netIncomeToCommon', models.BigIntegerField(blank=True, null=True)),
                ('openInterest', models.CharField(blank=True, max_length=100, null=True)),
                ('operatingCashflow', models.BigIntegerField(blank=True, null=True)),
                ('operatingMargins', models.FloatField(blank=True, null=True)),
                ('payoutRatio', models.FloatField(blank=True, null=True)),
                ('pegRatio', models.FloatField(blank=True, null=True)),
                ('priceToBook', models.FloatField(blank=True, null=True)),
                ('profitMargins', models.FloatField(blank=True, null=True)),
                ('quickRatio', models.FloatField(blank=True, null=True)),
                ('quoteType', models.CharField(blank=True, max_length=100, null=True)),
                ('returnOnAssets', models.FloatField(blank=True, null=True)),
                ('returnOnEquity', models.FloatField(blank=True, null=True)),
                ('revenueGrowth', models.FloatField(blank=True, null=True)),
                ('revenuePerShare', models.FloatField(blank=True, null=True)),
                ('revenueQuarterlyGrowth', models.FloatField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('sharesOutstanding', models.BigIntegerField(blank=True, null=True)),
                ('shortName', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('symbol', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('toCurrency', models.CharField(blank=True, max_length=100, null=True)),
                ('totalAssets', models.CharField(blank=True, max_length=100, null=True)),
                ('totalCash', models.BigIntegerField(blank=True, null=True)),
                ('totalCashPerShare', models.FloatField(blank=True, null=True)),
                ('totalDebt', models.BigIntegerField(blank=True, null=True)),
                ('totalRevenue', models.BigIntegerField(blank=True, null=True)),
                ('trailingAnnualDividendRate', models.FloatField(blank=True, null=True)),
                ('trailingAnnualDividendYield', models.FloatField(blank=True, null=True)),
                ('trailingEps', models.FloatField(blank=True, null=True)),
                ('trailingPE', models.FloatField(blank=True, null=True)),
                ('trailingPegRatio', models.FloatField(blank=True, null=True)),
                ('twoHundredDayAverage', models.FloatField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('ytdReturn', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
